// CWE id → short name lookup for display alongside the raw CWE id.
// Covers the CWEs commonly seen in Java library CVEs; unknown ids fall back to the id alone.
const CWE_NAMES_EN: Record<string, string> = {
  'CWE-20': 'Improper Input Validation',
  'CWE-22': 'Path Traversal',
  'CWE-44': 'Path Equivalence',
  'CWE-77': 'Command Injection',
  'CWE-78': 'OS Command Injection',
  'CWE-79': 'Cross-site Scripting (XSS)',
  'CWE-89': 'SQL Injection',
  'CWE-91': 'XML Injection',
  'CWE-94': 'Code Injection',
  'CWE-113': 'HTTP Response Splitting',
  'CWE-200': 'Exposure of Sensitive Information',
  'CWE-209': 'Information Exposure Through Error Message',
  'CWE-269': 'Improper Privilege Management',
  'CWE-287': 'Improper Authentication',
  'CWE-295': 'Improper Certificate Validation',
  'CWE-306': 'Missing Authentication for Critical Function',
  'CWE-352': 'Cross-Site Request Forgery (CSRF)',
  'CWE-362': 'Race Condition',
  'CWE-377': 'Insecure Temporary File',
  'CWE-384': 'Session Fixation',
  'CWE-400': 'Uncontrolled Resource Consumption',
  'CWE-404': 'Improper Resource Shutdown',
  'CWE-416': 'Use After Free',
  'CWE-434': 'Unrestricted Upload of File with Dangerous Type',
  'CWE-444': 'HTTP Request Smuggling',
  'CWE-470': 'Unsafe Reflection',
  'CWE-476': 'NULL Pointer Dereference',
  'CWE-502': 'Deserialization of Untrusted Data',
  'CWE-611': 'XML External Entity (XXE)',
  'CWE-613': 'Insufficient Session Expiration',
  'CWE-732': 'Incorrect Permission Assignment',
  'CWE-770': 'Allocation of Resources Without Limits',
  'CWE-776': 'XML Entity Expansion (Billion Laughs)',
  'CWE-787': 'Out-of-bounds Write',
  'CWE-829': 'Inclusion of Functionality from Untrusted Control Sphere',
  'CWE-835': 'Infinite Loop',
  'CWE-862': 'Missing Authorization',
  'CWE-863': 'Incorrect Authorization',
  'CWE-915': 'Improperly Controlled Modification of Object Attributes',
  'CWE-917': 'Expression Language Injection',
  'CWE-918': 'Server-Side Request Forgery (SSRF)',
  'CWE-1321': 'Prototype Pollution',
}

const CWE_NAMES_ZH: Record<string, string> = {
  'CWE-20': '输入验证不当',
  'CWE-22': '路径遍历',
  'CWE-44': '路径等价',
  'CWE-77': '命令注入',
  'CWE-78': '操作系统命令注入',
  'CWE-79': '跨站脚本攻击 (XSS)',
  'CWE-89': 'SQL 注入',
  'CWE-91': 'XML 注入',
  'CWE-94': '代码注入',
  'CWE-113': 'HTTP 响应拆分',
  'CWE-200': '敏感信息泄露',
  'CWE-209': '错误信息导致信息泄露',
  'CWE-269': '权限管理不当',
  'CWE-287': '身份认证不当',
  'CWE-295': '证书校验不当',
  'CWE-306': '关键功能缺少身份认证',
  'CWE-352': '跨站请求伪造 (CSRF)',
  'CWE-362': '竞态条件',
  'CWE-377': '不安全的临时文件',
  'CWE-384': '会话固定',
  'CWE-400': '资源消耗不受控制',
  'CWE-404': '资源释放不当',
  'CWE-416': '释放后使用',
  'CWE-434': '危险类型文件的无限制上传',
  'CWE-444': 'HTTP 请求走私',
  'CWE-470': '不安全的反射',
  'CWE-476': '空指针解引用',
  'CWE-502': '不可信数据反序列化',
  'CWE-611': 'XML 外部实体注入 (XXE)',
  'CWE-613': '会话过期不充分',
  'CWE-732': '权限分配不正确',
  'CWE-770': '资源分配无限制',
  'CWE-776': 'XML 实体扩展 (Billion Laughs)',
  'CWE-787': '越界写入',
  'CWE-829': '引入来自不可信控制域的功能',
  'CWE-835': '无限循环',
  'CWE-862': '缺少授权',
  'CWE-863': '授权不正确',
  'CWE-915': '对象属性修改控制不当',
  'CWE-917': '表达式语言注入',
  'CWE-918': '服务端请求伪造 (SSRF)',
  'CWE-1321': '原型污染',
}

export function cweName(cweId?: string | null, locale: string = 'zh-CN'): string {
  if (!cweId) return ''
  const key = cweId.trim().toUpperCase()
  const table = locale === 'en-US' ? CWE_NAMES_EN : CWE_NAMES_ZH
  return table[key] ?? ''
}
